// currency related
export const FETCH_CURRENCIES_REQUEST = 'FETCH_CURRENCIES_REQUEST'
export const FETCH_CURRENCIES_SUCCESS = 'FETCH_CURRENCIES_SUCCESS'
export const FETCH_CURRENCIES_ERROR = 'FETCH_CURRENCIES_ERROR'
export const CURRENCY_SELECTED = 'CURRENCY_SELECTED'

// weights and measures
export const UNITS_SELECTED = 'UNITS_SELECTED'

// ingredient related
export const CREATE_INGREDIENT = 'CREATE_INGREDIENT'
export const EDIT_INGREDIENT = 'EDIT_INGREDIENT'
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'
export const ASSIGN_INGREDIENT = 'ASSIGN_INGREDIENT'

// group related
export const CLEAR_GROUP = 'CLEAR_GROUP'
export const SIZE_GROUP = 'SIZE_GROUP'
