// currency related
export const FETCH_CURRENCIES_REQUEST = 'FETCH_CURRENCIES_REQUEST'
export const FETCH_CURRENCIES_SUCCESS = 'FETCH_CURRENCIES_SUCCESS'
export const FETCH_CURRENCIES_ERROR = 'FETCH_CURRENCIES_ERROR'
export const CURRENCY_SELECTED = 'CURRENCY_SELECTED'

// weights and measures
export const BASE_UNITS_SELECTED = 'BASE_UNITS_SELECTED'
export const UNITS_SELECTED = 'UNITS_SELECTED'

// ingredient related
export const CREATE_INGREDIENT = 'CREATE_INGREDIENT'
export const EDIT_INGREDIENT = 'EDIT_INGREDIENT'
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'
export const ASSIGN_INGREDIENT = 'ASSIGN_INGREDIENT'
export const OPEN_INGREDIENT = 'OPEN_INGREDIENT'
export const CLOSE_INGREDIENT = 'CLOSE_INGREDIENT'

// group related
export const CLEAR_GROUP = 'CLEAR_GROUP'
export const SIZE_GROUP = 'SIZE_GROUP'

// total quantity related
export const TOTAL_QUANTITY_CHANGE = 'TOTAL_QUANTITY_CHANGE'
export const TOTAL_QUANTITY_UNITS_CHANGE = 'TOTAL_QUANTITY_UNITS_CHANGE'
