// currency related
export const FETCH_CURRENCIES_REQUEST = 'FETCH_CURRENCIES_REQUEST'
export const FETCH_CURRENCIES_SUCCESS = 'FETCH_CURRENCIES_SUCCESS'
export const FETCH_CURRENCIES_ERROR = 'FETCH_CURRENCIES_ERROR'

// config related
export const UNIT_TYPES_SELECTED = 'UNIT_TYPES_SELECTED'
export const BASE_UNITS_SELECTED = 'BASE_UNITS_SELECTED'
export const BASE_CURRENCY_SELECTED = 'BASE_CURRENCY_SELECTED'
export const CURRENCY_DECIMAL_PLACES_SELECTED = 'CURRENCY_DECIMAL_PLACES_SELECTED'
export const UNIT_DECIMAL_PLACES_SELECTED = 'UNIT_DECIMAL_PLACES_SELECTED'
export const PERCENTAGE_DECIMAL_PLACES_SELECTED = 'PERCENTAGE_DECIMAL_PLACES_SELECTED'

// ingredient related
export const CREATE_INGREDIENT = 'CREATE_INGREDIENT'
export const EDIT_INGREDIENT = 'EDIT_INGREDIENT'
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'
export const ASSIGN_INGREDIENT = 'ASSIGN_INGREDIENT'
export const OPEN_INGREDIENT = 'OPEN_INGREDIENT'
export const CLOSE_INGREDIENT = 'CLOSE_INGREDIENT'

// model related
export const SET_MODEL_LIMIT_TYPE ='SET_MODEL_LIMIT_TYPE'
export const SET_MODEL_LIMITS = 'SET_MODEL_LIMITS'